// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel HelloWorld

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float3 _CameraPosition;
float4x4 _CameraToWorld;
float4x4 _CameraInverseProjection;

struct Sphere
{
    float3 position;
    float radius;
};

struct hitInfo
{
    float3 hitpoint;
    float3 normal;
};

struct Ray
{
    float3 rayOrigin;
    float3 rayDir;
    hitInfo HitInfo;
};

[numthreads(8,8,1)]
void HelloWorld(uint3 id : SV_DispatchThreadID)
{

    uint width;
    uint height;
    Result.GetDimensions(width, height);
    
    if (id.x >= width || id.y >= height)
    {
        return;
    }
    
    float2 uv = (id.xy + 0.5) / float2(width, height);
    float2 screenSpace = uv * 2.0 - 1.0;
    
    float4 viewTarget = mul(_CameraInverseProjection, float4(screenSpace, 1, 1));
    viewTarget /= viewTarget.w;
    
    float3 worldTarget = mul(_CameraToWorld, viewTarget).xyz;
    
    Ray ray;
    
    ray.rayOrigin = _CameraPosition;
    ray.rayDir = normalize(worldTarget - ray.rayOrigin);
    
    Result[id.xy] = float4(2*(ray.rayDir - 0.5), 1);
}
