// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel HelloWorld

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void HelloWorld (uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Result.GetDimensions(width,height);

    if (id.x >= width || id.y >= height)
    {
        return;
    }

    float2 uv = float2(id.x/(float)width,id.y/(float)height);

    float3 color = float3(uv.x,uv.y,0);

    Result[id.xy] = float4(color,1);
}
